/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PANELS;

import DAO.lopDAO;
import DAO.sinhVienDAO;
import MODELS.SinhVien;
import MODELS.Lop;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HAO
 */
public class SinhVienPanel extends javax.swing.JPanel {

    /**
     * Creates new form SinhVienPanel
     */
    List<SinhVien> listSV = new ArrayList<>();
    List<Lop> listLop = new ArrayList<>();

    public SinhVienPanel() {
        initComponents();
        loadDataToTable();
        loadDataToCBO();
    }

    public void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
        model.setRowCount(0);
        sinhVienDAO svDAO = new sinhVienDAO();
        listSV = svDAO.getALlSinhVien();
        for (SinhVien sv : listSV) {
            Object[] row = new Object[]{
                sv.getMaSV(), sv.getTenSV(), sv.getNamSinh(), sv.getSDT(), getTen(sv.getMaLop()), sv.getTuoi()
            };
            model.addRow(row);
        }
    }

    public void loadDataToCBO() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLop.getModel();
        model.removeAllElements();
        lopDAO lopDAO = new lopDAO();
        listLop = lopDAO.getAllLop();
        for (Lop lop : listLop) {
            model.addElement(lop);
        }
    }

    public String getTen(int maLop) {
        lopDAO lopDAO = new lopDAO();
        listLop = lopDAO.getAllLop();
        for (Lop lop : listLop) {
            if (lop.getMaLop() == maLop) {
                return lop.getTenLop();
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenSV = new javax.swing.JTextField();
        txtNamSinh = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        cboLop = new javax.swing.JComboBox<>();
        btnInit = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();

        jLabel2.setText("Năm Sinh");

        jLabel3.setText("Tên Sinh Viên");

        jLabel4.setText("Lớp");

        jLabel5.setText("SDT");

        jLabel6.setText("Tuổi");

        txtNamSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamSinhActionPerformed(evt);
            }
        });

        cboLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnInit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Add.png"))); // NOI18N
        btnInit.setText("Làm Mới");
        btnInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Repair.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Tên SV", "Năm Sinh", "SDT", "Lớp", "Tuổi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInit)
                                .addGap(18, 18, 18)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTenSV)
                            .addComponent(txtNamSinh)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInit)
                        .addComponent(btnThem)
                        .addComponent(btnXoa))
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamSinhActionPerformed

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        int row = tblSinhVien.getSelectedRow();
        SinhVien sv = listSV.get(row);
        txtTenSV.setText(sv.getTenSV());
        txtNamSinh.setText(String.valueOf(sv.getNamSinh()));
        txtSDT.setText(sv.getSDT());
        for (Lop lop : listLop) {
            if (lop.getMaLop() == sv.getMaLop()) {
                cboLop.setSelectedItem(lop);
                break;
            }
        }
        txtTuoi.setText(String.valueOf(sv.getTuoi()));
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitActionPerformed
        txtTenSV.setText("");
        txtNamSinh.setText("");
        txtTuoi.setText("");
        txtSDT.setText("");
        cboLop.setSelectedIndex(0);
    }//GEN-LAST:event_btnInitActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            String tenSV = txtTenSV.getText().trim();
            String tuoiStr = txtTuoi.getText().trim();
            String namSinhStr = txtNamSinh.getText().trim();
            String sdt = txtSDT.getText().trim();
            Lop lop = (Lop) cboLop.getSelectedItem();

            // Kiểm tra dữ liệu trống
            if (tenSV.isEmpty() || tuoiStr.isEmpty() || namSinhStr.isEmpty() || sdt.isEmpty() || lop == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sinh viên!");
                return;
            }

            // Kiểm tra số hợp lệ
            int tuoi = Integer.parseInt(tuoiStr);
            int namSinh = Integer.parseInt(namSinhStr);

            if (tuoi <= 0 || namSinh <= 0) {
                JOptionPane.showMessageDialog(this, "Tuổi và năm sinh phải là số nguyên dương!");
                return;
            }

            // Kiểm tra số điện thoại
            if (!sdt.matches("\\d{9,11}")) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ! (phải từ 9 đến 11 chữ số)");
                return;
            }

            // Tạo đối tượng sinh viên
            SinhVien sv = new SinhVien();
            sv.setTenSV(tenSV);
            sv.setTuoi(tuoi);
            sv.setNamSinh(namSinh);
            sv.setSDT(sdt);
            sv.setMaLop(lop.getMaLop());

            // Gọi DAO để thêm sinh viên
            sinhVienDAO svDAO = new sinhVienDAO();
            int index = svDAO.themSinhVien(sv);

            if (index > 0) {
                JOptionPane.showMessageDialog(this, "Thêm sinh viên thành công!");
                loadDataToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sinh viên thất bại!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tuổi và năm sinh phải là số nguyên!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm sinh viên: " + e.getMessage());
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblSinhVien.getSelectedRow();
        sinhVienDAO svDAO = new sinhVienDAO();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thẻ thư viện muốn xóa");
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thẻ thư viện này không?", "Hỏi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            try {
                SinhVien sv = listSV.get(row);
                int index = svDAO.xoaSinhVien(sv.getMaSV());
                if (index > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadDataToTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa thẻ thư viện");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tblSinhVien.getSelectedRow();
        sinhVienDAO svDAO = new sinhVienDAO();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thẻ thư viện muốn cập nhật");
            return;
        }

        try {
            String tenSV = txtTenSV.getText().trim();
            String tuoiStr = txtTuoi.getText().trim();
            String sdt = txtSDT.getText().trim();
            Lop lop = (Lop) cboLop.getSelectedItem();

            if (tenSV.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sinh viên!");
                return;
            }

            if (tuoiStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tuổi sinh viên!");
                return;
            }

            int tuoi = Integer.parseInt(tuoiStr);

            if (tuoi <= 0 || tuoi > 150) {
                JOptionPane.showMessageDialog(this, "Tuổi không hợp lệ! (1 - 150)");
                return;
            }

            if (sdt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại!");
                return;
            }

            if (!sdt.matches("\\d{9,11}")) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ! (phải từ 9 đến 11 chữ số)");
                return;
            }

            if (lop == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp!");
                return;
            }

            SinhVien sv = listSV.get(row);
            sv.setTenSV(tenSV);
            sv.setTuoi(tuoi);

            // Nếu bạn muốn tính năm sinh từ tuổi (ví dụ hiện tại là 2025)
            int currentYear = java.time.Year.now().getValue();
            int namSinh = currentYear - tuoi;
            sv.setNamSinh(namSinh);

            sv.setSDT(sdt);
            sv.setMaLop(lop.getMaLop());

            int index = svDAO.capNhatSinhVien(sv);
            if (index > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật thẻ thư viện thành công");
                loadDataToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thẻ thư viện thất bại");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tuổi phải là số nguyên!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật thẻ thư viện: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInit;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenSV;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
