/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import PANELS.NXB;
import PANELS.PhieuMuon;
import PANELS.Sach;
import PANELS.SinhVienPanel;
import PANELS.TimKiem;
import PANELS.ThongKe;
import PANELS.ThuThuPanel;
import PANELS.TrangChu;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author HAO
 */
public class frm_Main extends javax.swing.JFrame {

    /**
     * Creates new form frm_Main
     */
    public frm_Main() {
        JPanel panelTrangChu = new JPanel();
        JPanel panelSach = new JPanel();
        SinhVienPanel panelSinhVien = null;
        JPanel panelTacGia = new JPanel();
        NXB panelNhaXuatBan = null;
        JPanel panelThuThu = new JPanel();
        PhieuMuon panelPhieuMuon = null;
        TimKiem panelTimKiem = null;
        ThongKe panelThongKe = null;

        try {
            initComponents();
            initializeButtons();
            pnMain.setLayout(new CardLayout());

            panelTrangChu = new TrangChu();
            panelSach = new Sach();
            panelSinhVien= new SinhVienPanel();
            panelTacGia.add(new JLabel("Đây là trang Tác Giả"));
            panelNhaXuatBan= new NXB();
            panelThuThu = new ThuThuPanel();
            panelPhieuMuon = new PhieuMuon();
            panelTimKiem = new TimKiem();
            panelThongKe = new ThongKe();

        } catch (Exception e) {
            e.printStackTrace();
        }

        // Thêm các panel vào pnMain với tên định danh
        CardLayout cl = (CardLayout) pnMain.getLayout();
        pnMain.add(panelTrangChu, "TrangChu");
        pnMain.add(panelSach, "Sach");
        pnMain.add(panelTacGia, "TacGia");
        pnMain.add(panelThuThu, "ThuThu");
        if(panelSinhVien!=null){
            pnMain.add(panelSinhVien,"SinhVien");
        }
        if (panelPhieuMuon != null) {
            pnMain.add(panelPhieuMuon, "PhieuMuon");
        }
        if (panelTimKiem != null) {
            pnMain.add(panelTimKiem, "TimKiem");
        }
        if(panelNhaXuatBan!=null){
            pnMain.add(panelNhaXuatBan,"NhaXuatBan");
        }
        pnMain.add(panelThongKe, "ThongKe");
    }

    // Khai báo mảng chứa các nút
    private JButton[] buttons;

    private void initializeButtons() {
        buttons = new JButton[]{
            btnDangXuat, btnNhaXuatBan, btnPhieuMuon, btnTimKiem, btnSach,
            btnSinhVien, btnThongKe, btnThuThu, btnTrangChu
        };
    }

    // Hàm reset màu nền về mặc định (null hoặc màu bạn muốn)
    private void resetButtonColors() {
        for (JButton btn : buttons) {
            btn.setBackground(null); // Hoặc btn.setBackground(Color.DEFAULT nếu bạn định nghĩa
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFull = new javax.swing.JPanel();
        btnSach = new javax.swing.JButton();
        btnSinhVien = new javax.swing.JButton();
        pnLeft = new javax.swing.JLabel();
        btnNhaXuatBan = new javax.swing.JButton();
        btnThuThu = new javax.swing.JButton();
        btnPhieuMuon = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnFull.setBackground(new java.awt.Color(51, 51, 51));
        pnFull.setForeground(new java.awt.Color(51, 51, 51));

        btnSach.setBackground(new java.awt.Color(51, 51, 51));
        btnSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSach.setForeground(new java.awt.Color(255, 255, 255));
        btnSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/bookicon.png"))); // NOI18N
        btnSach.setText("Sách");
        btnSach.setBorder(null);
        btnSach.setContentAreaFilled(false);
        btnSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSach.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSach.setIconTextGap(12);
        btnSach.setOpaque(true);
        btnSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachActionPerformed(evt);
            }
        });

        btnSinhVien.setBackground(new java.awt.Color(51, 51, 51));
        btnSinhVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSinhVien.setForeground(new java.awt.Color(255, 255, 255));
        btnSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Readericon.png"))); // NOI18N
        btnSinhVien.setText("Thẻ Thư Viện");
        btnSinhVien.setBorder(null);
        btnSinhVien.setContentAreaFilled(false);
        btnSinhVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSinhVien.setIconTextGap(12);
        btnSinhVien.setOpaque(true);
        btnSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhVienActionPerformed(evt);
            }
        });

        pnLeft.setBackground(new java.awt.Color(51, 51, 51));
        pnLeft.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnLeft.setForeground(new java.awt.Color(255, 255, 255));
        pnLeft.setText("Thư Viện HUIT");

        btnNhaXuatBan.setBackground(new java.awt.Color(51, 51, 51));
        btnNhaXuatBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhaXuatBan.setForeground(new java.awt.Color(255, 255, 255));
        btnNhaXuatBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/nhaxuatban.png"))); // NOI18N
        btnNhaXuatBan.setText("Nhà Xuất Bản");
        btnNhaXuatBan.setBorder(null);
        btnNhaXuatBan.setContentAreaFilled(false);
        btnNhaXuatBan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhaXuatBan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhaXuatBan.setIconTextGap(3);
        btnNhaXuatBan.setOpaque(true);
        btnNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaXuatBanActionPerformed(evt);
            }
        });

        btnThuThu.setBackground(new java.awt.Color(51, 51, 51));
        btnThuThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThuThu.setForeground(new java.awt.Color(255, 255, 255));
        btnThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Staff.png"))); // NOI18N
        btnThuThu.setText("Thủ Thư");
        btnThuThu.setBorder(null);
        btnThuThu.setContentAreaFilled(false);
        btnThuThu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThuThu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThuThu.setOpaque(true);
        btnThuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuThuActionPerformed(evt);
            }
        });

        btnPhieuMuon.setBackground(new java.awt.Color(51, 51, 51));
        btnPhieuMuon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Note.png"))); // NOI18N
        btnPhieuMuon.setText("Phiếu Mượn");
        btnPhieuMuon.setBorder(null);
        btnPhieuMuon.setContentAreaFilled(false);
        btnPhieuMuon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhieuMuon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPhieuMuon.setIconTextGap(8);
        btnPhieuMuon.setOpaque(true);
        btnPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuMuonActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(51, 51, 51));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/search.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setBorder(null);
        btnTimKiem.setContentAreaFilled(false);
        btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTimKiem.setIconTextGap(20);
        btnTimKiem.setOpaque(true);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(51, 51, 51));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Exit.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setBorder(null);
        btnDangXuat.setContentAreaFilled(false);
        btnDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangXuat.setIconTextGap(9);
        btnDangXuat.setOpaque(true);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(51, 51, 51));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Combo Chart.png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setBorder(null);
        btnThongKe.setContentAreaFilled(false);
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThongKe.setIconTextGap(6);
        btnThongKe.setOpaque(true);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnTrangChu.setBackground(new java.awt.Color(51, 51, 51));
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8-home-48.png"))); // NOI18N
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setBorder(null);
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.setContentAreaFilled(false);
        btnTrangChu.setFocusPainted(false);
        btnTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrangChu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTrangChu.setOpaque(true);
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        pnMain.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnFullLayout = new javax.swing.GroupLayout(pnFull);
        pnFull.setLayout(pnFullLayout);
        pnFullLayout.setHorizontalGroup(
            pnFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFullLayout.createSequentialGroup()
                .addGroup(pnFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhaXuatBan)
                    .addGroup(pnFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnFullLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(btnSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThuThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 319, Short.MAX_VALUE)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnFullLayout.setVerticalGroup(
            pnFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFullLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTrangChu)
                .addGap(30, 30, 30)
                .addComponent(btnSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSinhVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThuThu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPhieuMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangXuat)
                .addGap(30, 30, 30))
            .addGroup(pnFullLayout.createSequentialGroup()
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(pnFull, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.setVisible(false);
        frm_Login login = new frm_Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        resetButtonColors();
        btnThongKe.setBackground(Color.BLUE);
        CardLayout cl = (CardLayout) pnMain.getLayout();
        cl.show(pnMain, "ThongKe");
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        resetButtonColors();
        btnTimKiem.setBackground(Color.BLUE);
        CardLayout cl = (CardLayout) pnMain.getLayout();
        cl.show(pnMain, "TimKiem");
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuMuonActionPerformed
        resetButtonColors();
        btnPhieuMuon.setBackground(Color.BLUE);
        CardLayout cl = (CardLayout) pnMain.getLayout();
        cl.show(pnMain, "PhieuMuon");
    }//GEN-LAST:event_btnPhieuMuonActionPerformed

    private void btnThuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuThuActionPerformed
        resetButtonColors();
        btnThuThu.setBackground(Color.BLUE);
        CardLayout cl = (CardLayout) pnMain.getLayout();
        cl.show(pnMain, "ThuThu");
    }//GEN-LAST:event_btnThuThuActionPerformed

    private void btnNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaXuatBanActionPerformed
        resetButtonColors();
        btnNhaXuatBan.setBackground(Color.BLUE);
        CardLayout cl = (CardLayout) pnMain.getLayout();
        cl.show(pnMain, "NhaXuatBan");
    }//GEN-LAST:event_btnNhaXuatBanActionPerformed

    private void btnSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhVienActionPerformed
        resetButtonColors();
        btnSinhVien.setBackground(Color.BLUE);
        CardLayout cl = (CardLayout) pnMain.getLayout();
        cl.show(pnMain, "SinhVien");
    }//GEN-LAST:event_btnSinhVienActionPerformed

    private void btnSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSachActionPerformed
        resetButtonColors();
        btnSach.setBackground(Color.BLUE);
        CardLayout cl = (CardLayout) pnMain.getLayout();
        cl.show(pnMain, "Sach");
    }//GEN-LAST:event_btnSachActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        resetButtonColors();
        btnTrangChu.setBackground(Color.BLUE);
        CardLayout cl = (CardLayout) pnMain.getLayout();
        cl.show(pnMain, "TrangChu");
    }//GEN-LAST:event_btnTrangChuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Main().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnNhaXuatBan;
    private javax.swing.JButton btnPhieuMuon;
    private javax.swing.JButton btnSach;
    private javax.swing.JButton btnSinhVien;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThuThu;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JPanel pnFull;
    private javax.swing.JLabel pnLeft;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
